import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="bg-slate-400 border-2 border-purple-400 h-screen w-[90%] mx-auto flex flex-col justify-between">
					<header className="h-[5%] border-2 border-black">
						<div className="headercontent">Header</div>
					</header>
					<main className="border-2 border-blue-700 flex h-full">
						<div className="contentwrapper border-2 border-orange-500 flex flex-1 justify-center items-center">
							<div className="content border-2 border-black">
								<section>
									{children}
								</section>
							</div>
						</div>
					</main>
					<footer className=" w-full">
						<div className="footercontent bg-black flex justify-around border-2 border-white">
							<div className="w-80 h-8 bg-slate-500 border-white border-2">Footer stuff</div>
							<div className="w-80 h-8 bg-slate-500 border-white border-2">Footer things</div>
							<div className="w-80 h-8 bg-slate-500 border-white border-2">Oh my GOD what is THAT!!!?!?</div>
						</div>
					</footer>
					{/* <pre>{JSON.stringify(data, null, 2)}</pre> */}
				</div>
			</body>
		</html>
	)
}
